# fly.toml app configuration file generated for bot-w-drive-sotarge on 2025-04-24T12:51:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-w-drive-sotarge'
primary_region = 'cdg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
    port = 8080
    handlers = ["http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "python telegram_bot_prod_v2.py"